name: Debian Package CI

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      go_version:
        required: false
        type: string
        default: '1.21'
      apt_repo:
        required: true
        type: string
      distribution:
        required: false
        type: string
        default: 'stable'
      component:
        required: false
        type: string
        default: 'main'
    secrets:
      gpg_passphrase:
        required: true
      repo_token:
        required: true

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go_version }}
      - run: |
          sudo apt-get update
          sudo apt-get install -y build-essential fakeroot dpkg-dev gnupg2
      - uses: actions/checkout@v3
        with:
          repository: Dastagirireddy/github-actions-templates
          path: .github/scripts
          token: ${{ secrets.repo_token }}
      - run: |
          chmod +x .github/scripts/*.sh
          mkdir -p scripts
          cp .github/scripts/*.sh scripts/
      - run: |
          ./scripts/setup-gpg.sh \
            "Dastagirireddy" \
            "dastagirireddy99.r@gmail.com" \
            "${{ secrets.gpg_passphrase }}"
        env:
          GNUPGHOME: /tmp/gnupg
      - run: |
          ./scripts/build-deb.sh "${{ inputs.app_name }}"
        env:
          VERSION: ${{ github.ref_name }}
      - uses: actions/upload-artifact@v3
        with:
          name: deb-package
          path: build/deb/*.deb
      - if: startsWith(github.ref, 'refs/tags/')
        run: |
          git clone https://${{ secrets.repo_token }}@github.com/${{ inputs.apt_repo }}.git apt-repo
          cd apt-repo
          gpg --import /tmp/gnupg/private.asc
          gpg --import /tmp/gnupg/public.asc
          mkdir -p pool/${{ inputs.distribution }}/${{ inputs.component }}
          cp ../build/deb/*.deb pool/${{ inputs.distribution }}/${{ inputs.component }}/
          apt-ftparchive packages . > Packages
          gzip -k -f Packages
          apt-ftparchive release . > Release
          gpg --clearsign -o InRelease Release
          gpg -abs -o Release.gpg Release
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Add ${{ inputs.app_name }} ${{ github.ref_name }}"
          git push origin main
